all: fw.c
		gcc -Wall -g -o fw fw.c hashtable.c linkedlist.c safe_mem_functions.c readword.c
fw:	 fw.c
		gcc -Wall -g -o fw fw.c hashtable.c linkedlist.c safe_mem_functions.c readword.c
clean:
		rm fw